[package]
name = "treegen"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.24.7"
imageproc = { version = "0.23.0", features = ["display-window"] }
num-complex = "0.4.4"
rand = "0.8.5"
rand_distr = "0.4.3"
